### ISSUE TITLE
Missing missiles

### ISSUE THREAD

**Issue by opensdh** [bin0al/bin0al.github.io#1]
The missles overlay is missing two packs:

1. Early Supers Room
1. Alpha Power Bomb Room

**Comment by bin0al** [comment]
Nice catch! Just added these, thank you!

**Comment by opensdh** [comment]
Sorry: one more, the Lower Norfair Spring Ball Maze Room.

**Comment by bin0al** [comment]
Sorry, got the notification for this one and then forgot all about it! I'll be adding this one later today as well; Thanks again for the info, it's extremely helpful! I'm also going to give the item lists a quick once-over to compare my item counts to the counts in the game; This should make sure I haven't missed more items.

**Comment by bin0al** [comment]
A bit delayed, but the additional missile pack in Lower Norfair Spring Ball Maze Room has been added, and I also verified item counts; All counts were correct except for missiles, where I had an extra pack; It was stacked on top of another pack in First Missile Room. Thanks again for pointing these out!
